package {

import com.threerings.util.RandomUtil;

public class Items
{
    // Item slots, each of which can wear one item
    public static const BACK :int = 0;
    public static const FEET :int = 1;
    public static const LEGS :int = 2;
    public static const TORSO :int = 3;
    public static const HEAD :int = 4;
    public static const HAND :int = 5;

    // Item categories, for class-based bonuses
    public static const NONE :int = -1;
    public static const ARCANE :int = 0;
    public static const LIGHT :int = 1;
    public static const HEAVY :int = 2;

    public static const BOW :int = 3;
    public static const CLUB :int = 4;
    public static const AXE :int = 5;
    public static const SWORD :int = 6;
    public static const SPEAR :int = 7;
    public static const MAGIC :int = 8;
    public static const DAGGER :int = 9;

    /** The big kahuna. */
    public static const TABLE :Array = [
        // [ sprite, name, slot, category, power ]
        [ 94, "Loincloth", TORSO, NONE, 1 ],
        [ 95, "Acolyte's Robe", TORSO, ARCANE, 3 ],
        [ 96, "Woodsman's Leathers", TORSO, LIGHT, 1 ],
        [ 97, "Legionnaire's Armor", TORSO, LIGHT, 4 ],
        [ 98, "Bling-Encrusted Plate", TORSO, HEAVY, 10 ],
        [ 99, "Elegant Dress", TORSO, NONE, 8 ],
        [ 100, "Soruda's Shell", TORSO, LIGHT, 10 ],
        [ 101, "Steel Plate", TORSO, LIGHT, 3 ],
        [ 102, "Shoulder Pads", TORSO, LIGHT, 4 ],
        [ 103, "Chain Sash", TORSO, HEAVY, 2 ],
        [ 104, "The Sultan's Favorite", TORSO, NONE, 4 ],
        [ 105, "Torn Robe", TORSO, ARCANE, 1 ],
        [ 106, "Apprentice Robe", TORSO, ARCANE, 2 ],
        [ 107, "Koopa Armor", TORSO, LIGHT, 6 ],
        [ 108, "Shredder's Armor", TORSO, HEAVY, 7 ],
        [ 109, "Plate of the Valkyrie", TORSO, HEAVY, 1 ],
        [ 110, "Chain Mail", TORSO, LIGHT, 2 ],
        [ 111, "Shining Mail", TORSO, LIGHT, 5 ],
        [ 112, "Chain Shirt", TORSO, LIGHT, 4 ],
        [ 113, "Royal Tabbard", TORSO, NONE, 5 ],
        [ 114, "Royal Guard's Armor", TORSO, LIGHT, 6 ],
        [ 115, "Gladiator's Prize", TORSO, LIGHT, 8 ],
        [ 116, "Harlequin Attire", TORSO, NONE, 10 ],
        [ 117, "Harlequin Attire", TORSO, NONE, 8 ],
        [ 118, "Crystal Armor", TORSO, HEAVY, 10 ],
        [ 126, "Water Talisman", TORSO, ARCANE, 3 ],
        [ 127, "Earth Talisman", TORSO, ARCANE, 4 ],
        [ 128, "Air Talisman", TORSO, ARCANE, 5 ],
        [ 129, "Cheap Knockoff Talisman", TORSO, ARCANE, 1 ],
        [ 130, "Turquoise Talisman", TORSO, ARCANE, 6 ],
        [ 131, "Amethyst Talisman", TORSO, ARCANE, 7 ],
        [ 132, "Diamond Talisman", TORSO, ARCANE, 8 ],
        [ 133, "Druid's Robe", TORSO, ARCANE, 8 ],
        [ 134, "White Dress", TORSO, NONE, 1 ],
        [ 135, "Ectoplasmic Armor", TORSO, HEAVY, 10 ],
        [ 136, "Peasant's Vest", TORSO, HEAVY, 1 ],
        [ 137, "The Ghost Hunter", TORSO, ARCANE, 3 ],
        [ 138, "Archon's Mantle", TORSO, ARCANE, 10 ],
        [ 139, "Smith's Finery", TORSO, NONE, 3 ],
        [ 140, "Lizard Hide", TORSO, NONE, 2 ],
        [ 141, "Tunic of the Hood", TORSO, LIGHT, 4 ],
        [ 142, "Steel Plate", TORSO, HEAVY, 4 ],
        [ 143, "Commander's Plate", TORSO, HEAVY, 5 ],
        [ 144, "Steel Plate", TORSO, HEAVY, 6 ],
        [ 145, "The Stylish Monk", TORSO, NONE, 5 ],
        [ 146, "Pottage-Stained Vest", TORSO, NONE, 1 ],
        [ 147, "Bronze Armor", TORSO, HEAVY, 1 ],
        [ 148, "Rock Armor", TORSO, HEAVY, 1 ],
        [ 149, "Robe of the Sorceress", TORSO, ARCANE, 7 ],
        [ 150, "Karate Master Gi", TORSO, NONE, 10 ],
        [ 151, "Karate Gi", TORSO, NONE, 7 ],
        [ 152, "Gold Mail", TORSO, LIGHT, 7 ],
        [ 153, "Carpenter's Armor", TORSO, NONE, 2 ],
        [ 154, "Archer's Leathers", TORSO, LIGHT, 6 ],
        [ 155, "Rusty Plate", TORSO, HEAVY, 2 ],
        [ 156, "Fresh Alligator Skin Vest", TORSO, LIGHT, 3 ],
        [ 157, "Bronze Plate", TORSO, LIGHT, 2 ],
        [ 158, "Humble Vest", TORSO, LIGHT, 1 ],
        [ 159, "Bone Laced Garments", TORSO, ARCANE, 9 ],
        [ 160, "Ruby Carapace", TORSO, HEAVY, 8 ],
        [ 161, "Scholar's Garments", TORSO, ARCANE, 5 ],
        [ 162, "Studded Leather", TORSO, LIGHT, 2 ],
        [ 163, "Hunter's Gear", TORSO, LIGHT, 1 ],
        [ 164, "Tavern Keeper's Finery", TORSO, NONE, 3 ],
        [ 165, "Knotted Black Vest", TORSO, NONE, 1 ],
        [ 166, "Knotted Red Vest", TORSO, NONE, 1 ],
        [ 167, "Blessed Plate", TORSO, HEAVY, 4 ],
        [ 168, "Robe of the Viper", TORSO, ARCANE, 4 ],
        [ 169, "Robe of the Viper", TORSO, ARCANE, 6 ],
        [ 170, "The Yoke", TORSO, NONE, 4 ],
        [ 171, "Secret Agent Attire", TORSO, NONE, 6 ],
        [ 172, "Dungeon Master's T-Shirt", TORSO, NONE, 8 ],
        [ 173, "Knight's Armor", TORSO, HEAVY, 6 ],
        [ 174, "Cleric's Armor", TORSO, HEAVY, 7 ],
        [ 175, "Officer's Armor", TORSO, HEAVY, 8 ],
        [ 176, "Dark Knight's Armor", TORSO, HEAVY, 10 ],
        [ 177, "Iron Plate", TORSO, HEAVY, 2 ],
        [ 178, "Dragon's Hide", TORSO, LIGHT, 10 ],
        [ 178, "Occult Overseer", TORSO, ARCANE, 5 ],
        [ 180, "Hooded Occult Robe", TORSO, ARCANE, 3 ],
        [ 181, "Occult Robe", TORSO, ARCANE, 1 ],
        [ 182, "Night Bringer's Robe", TORSO, ARCANE, 9 ],
        [ 183, "Day Bringer's Robe", TORSO, ARCANE, 9 ],
        [ 184, "Apprentice of Water", TORSO, ARCANE, 2 ],
        [ 185, "Master of Water", TORSO, ARCANE, 4 ],
        [ 186, "Master of Earth", TORSO, ARCANE, 5 ],
        [ 187, "Apprentice of Earth", TORSO, ARCANE, 3 ],
        [ 188, "Gold Robe", TORSO, ARCANE, 1 ],
        [ 189, "Cyan Robe", TORSO, ARCANE, 1 ],
        [ 190, "Apprentice of Necromancy", TORSO, ARCANE, 4 ],
        [ 191, "Master of Nature", TORSO, ARCANE, 10 ],
        [ 192, "Apprentice of Nature", TORSO, ARCANE, 6 ],
        [ 193, "Pink Robe", TORSO, ARCANE, 1 ],
        [ 194, "Master of Necromancy", TORSO, ARCANE, 8 ],
        [ 195, "Violet Robe", TORSO, ARCANE, 1 ],
        [ 196, "Painter's Robe", TORSO, ARCANE, 2 ],
        [ 197, "Master of Fire", TORSO, ARCANE, 7 ],
        [ 198, "Master of the Sun", TORSO, ARCANE, 8 ],
        [ 199, "Royal Vestments", TORSO, ARCANE, 3 ],
        [ 200, "Apprentice of Fire", TORSO, ARCANE, 5 ],
        [ 201, "Dusk Walker's Robe", TORSO, ARCANE, 7 ],
        [ 202, "Time Bender's Robe", TORSO, ARCANE, 8 ],
        [ 203, "White Robe", TORSO, ARCANE, 1 ],
        [ 204, "Splicer's Robe", TORSO, ARCANE, 6 ],
        [ 205, "Apprentice of the Sun", TORSO, ARCANE, 4 ],
        [ 206, "Sailor Moon Outfit", TORSO, NONE, 6 ], // LOL
        [ 207, "Grave Robber's Coat", TORSO, NONE, 4 ],
        [ 208, "Fladnag's Robe", TORSO, ARCANE, 8 ],
        [ 209, "Scalemail", TORSO, HEAVY, 5 ],
        [ 210, "Heavy Chainmail", TORSO, HEAVY, 6 ],
        [ 211, "Samurai Armor", TORSO, HEAVY, 2 ],
        // Skipping a bunch of generic shit
        [ 222, "Mantle of the Possessed", TORSO, HEAVY, 4 ],
        [ 223, "Scholar's Robe", TORSO, ARCANE, 2 ],
        [ 224, "Leather Trenchcoat", TORSO, LIGHT, 7 ],
        [ 225, "Mantle of the Possessor", TORSO, HEAVY, 6 ],
        [ 226, "Dragon Scale Armor", TORSO, LIGHT, 6 ],
        [ 227, "Servant's Coat", TORSO, NONE, 5 ],
        [ 228, "Firebrand's Cause", TORSO, LIGHT, 3 ],
        [ 229, "Robe of the Exiled", TORSO, ARCANE, 2 ],

        [ 230, "Gladiator's Boots", FEET, LIGHT, 10 ],
        [ 231, "Royal Boots", FEET, LIGHT, 8 ],
        [ 232, "White Heels", FEET, NONE, 4 ],
        [ 233, "Black Sandals", FEET, NONE, 2 ],
        [ 234, "Blue Sandals", FEET, NONE, 3 ],
        [ 235, "Red Sandals", FEET, NONE, 3 ],
        [ 236, "White Sandals", FEET, NONE, 2 ],
        [ 237, "Leather Boots", FEET, LIGHT, 4 ],
        [ 238, "Cowboy Boots", FEET, LIGHT, 6 ],
        [ 239, "Gold Boots", FEET, LIGHT, 8 ],
        [ 240, "Moon Boots", FEET, ARCANE, 8 ],
        [ 241, "Iron Boots", FEET, HEAVY, 8 ],
        [ 242, "Jack Boots", FEET, LIGHT, 5 ],
        [ 243, "Leather Shoes", FEET, LIGHT, 1 ],
        [ 244, "Tap Dancing Shoes", FEET, NONE, 1 ],
        [ 245, "Black Slippers", FEET, NONE, 1 ],
        [ 246, "Brown Slippers", FEET, NONE, 1 ],
        [ 247, "Blue Slippers", FEET, NONE, 1 ],
        [ 248, "Red Slippers", FEET, NONE, 1 ],

        [ 286, "Short Sword", HAND, SWORD, 1 ],
        [ 287, "Guard's Axe", HAND, AXE, 3 ],
        [ 288, "Blade", HAND, DAGGER, 2 ],
        [ 289, "Sun Staff", HAND, MAGIC, 3 ],
        [ 290, "Hammer", HAND, CLUB, 2 ],
        [ 291, "The Tentacle Cleaver", HAND, AXE, 7 ],
        [ 292, "Double Axe", HAND, AXE, 4 ],
        [ 293, "Executioner's Axe", HAND, AXE, 6 ],
        [ 294, "Viking Axe", HAND, AXE, 8 ],
        [ 295, "Cleaver", HAND, AXE, 2 ],
        [ 296, "Hatchet", HAND, AXE, 1 ],
        [ 297, "Grizzly Axe", HAND, AXE, 9 ],
        [ 298, "Night Stick", HAND, CLUB, 2 ],
        [ 299, "The Morale Improver", HAND, DAGGER, 10 ],
        [ 300, "Double Katars", HAND, DAGGER, 9 ],
        [ 301, "Obsidian Blade", HAND, SWORD, 7 ],
        [ 302, "Letter Opener", HAND, DAGGER, 1 ],
        [ 303, "Poor Yorick", HAND, MAGIC, 5 ],
        [ 304, "Sword", HAND, SWORD, 1 ],
        [ 305, "Half-brick in a Sock", HAND, CLUB, 2 ],
        [ 306, "Short Bow", HAND, BOW, 1 ],
        [ 307, "Long Bow", HAND, BOW, 5 ],
        [ 308, "Thundering Bow", HAND, BOW, 10 ],
        [ 309, "Composite Bow", HAND, BOW, 3 ],
        [ 311, "The Whirled Hacker", HAND, SWORD, 10 ],
        [ 312, "Blue Dagger", HAND, SWORD, 1 ],
        [ 313, "The Ugly Stick", HAND, CLUB, 9 ],
        [ 314, "Club", HAND, CLUB, 1 ],
        [ 315, "Bludgeon", HAND, CLUB, 2 ],
        [ 316, "Baseball Bat", HAND, CLUB, 3 ],
        [ 317, "Heavy Crossbow", HAND, BOW, 6 ],
        [ 318, "Light Crossbow", HAND, BOW, 3 ],
        [ 319, "Soldier's Crossbow", HAND, BOW, 5 ],
        [ 320, "Burning Crossbow", HAND, BOW, 10 ],
        [ 321, "Crossbow", HAND, BOW, 2 ],
        [ 322, "Crystal Ball", HAND, MAGIC, 1 ],
        [ 323, "Butter Knife", HAND, DAGGER, 1 ],
        [ 324, "Dagger", HAND, DAGGER, 1 ],
        [ 326, "Dervish's Whirler", HAND, SPEAR, 4 ],
        [ 327, "Darts", HAND, BOW, 6 ],
        [ 329, "Golden Helix Staff", HAND, MAGIC, 10 ],
        [ 330, "Blue Blade", HAND, SWORD, 8 ],
        [ 331, "Long Sword", HAND, SWORD, 4 ],
        [ 332, "Qiang Spear", HAND, SPEAR, 6 ],
        [ 333, "Morning Star", HAND, CLUB, 7 ],
        [ 334, "Scimitar", HAND, SWORD, 3 ],
        [ 336, "Farmer's Scythe", HAND, SPEAR, 3 ],
        [ 337, "Blue Fire", HAND, MAGIC, 2 ],
        [ 338, "Static Charge", HAND, MAGIC, 4 ],
        [ 339, "Liquid Flame", HAND, MAGIC, 5 ],
        [ 340, "Acid Burst", HAND, MAGIC, 6 ],
        [ 341, "Glowing Embers", HAND, MAGIC, 7 ],
        [ 342, "Faerie Dust", HAND, MAGIC, 8 ],
        [ 343, "Twister", HAND, MAGIC, 10 ],
        [ 344, "Lightsaber", HAND, SWORD, 9 ],
        [ 345, "Forked Spear", HAND, SPEAR, 2 ],
        [ 346, "Spiked Flail", HAND, CLUB, 2 ],
        [ 347, "Ball and Chain", HAND, CLUB, 3 ],
        [ 348, "American Gladiators Staff", HAND, CLUB, 4 ],
        [ 349, "Flail", HAND, CLUB, 1 ],
        [ 350, "Double Flail", HAND, CLUB, 3 ],
        [ 351, "Heavy Flail", HAND, CLUB, 4 ],
        [ 352, "Nunchaku", HAND, DAGGER, 2 ],
        [ 353, "Nunchaku", HAND, DAGGER, 6 ],
        [ 354, "Knife", HAND, DAGGER, 2 ],
        [ 356, "Goblin's Club", HAND, CLUB, 3 ],
        [ 357, "Hobgoblin's Club", HAND, CLUB, 4 ],
        [ 358, "Orc's Club", HAND, CLUB, 7 ],
        [ 359, "Giant's Club", HAND, CLUB, 10 ],
        [ 360, "Warhammer", HAND, CLUB, 8 ],
        [ 361, "Poleaxe", HAND, AXE, 9 ],
        [ 362, "Polearm", HAND, SPEAR, 9 ],
        [ 363, "Blue Voulge", HAND, SPEAR, 10 ],
        [ 364, "Voulge", HAND, SPEAR, 5 ],
        [ 365, "Ogre Axe", HAND, AXE, 9 ],
        [ 366, "Toothed Bow", HAND, BOW, 7 ],
        [ 367, "Cobra Staff", HAND, MAGIC, 4 ],
        [ 368, "Broad Sword", HAND, SWORD, 5 ],
        [ 369, "Falchion", HAND, SWORD, 3 ],
        [ 370, "Halberd", HAND, SPEAR, 5 ],
        [ 374, "Tomahawk", HAND, AXE, 2 ],
        [ 376, "Giant Sword", HAND, SWORD, 6 ],
        [ 377, "Pig Sticker", HAND, SPEAR, 7 ],
        [ 379, "Shining Long Sword", HAND, SWORD, 8 ],
        [ 380, "Rapier", HAND, SWORD, 6 ],
        [ 381, "Katana", HAND, SWORD, 6 ],
        [ 382, "Dirk", HAND, DAGGER, 4 ],
        [ 383, "Ceremonial Bow", HAND, BOW, 6 ],
        [ 384, "Lance", HAND, SPEAR, 6 ],
        [ 385, "War Lance", HAND, SPEAR, 7 ],
        [ 388, "Long Sword of Intense Longness", HAND, SWORD, 4 ],
        [ 389, "Hunter's Bow", HAND, BOW, 2 ],
        [ 390, "Fist of Ice", HAND, MAGIC, 4 ],
        [ 391, "Fist of Flame", HAND, MAGIC, 6 ],
        [ 392, "Fist of the Sun", HAND, MAGIC, 8 ],
        [ 393, "Claymore", HAND, SWORD, 3 ],
        [ 394, "Long Sword", HAND, SWORD, 2 ],
        [ 395, "Scepter", HAND, CLUB, 2 ],
        [ 396, "Dark Scepter", HAND, CLUB, 5 ],
        [ 404, "Inanimate Carbon Rod", HAND, CLUB, 3 ],
        [ 405, "The Light Soaker", HAND, MAGIC, 7 ],
        [ 406, "Pickaxe", HAND, AXE, 2 ],
        [ 407, "Pitch Fork", HAND, SPEAR, 3 ],
        [ 408, "Mythical Sword", HAND, SWORD, 8 ],
        [ 409, "Pronged Spear", HAND, SPEAR, 2 ],
        [ 410, "Walking Stick", HAND, SPEAR, 1 ],
        [ 411, "Bo Staff", HAND, SPEAR, 4 ],
        [ 415, "Sword", HAND, SWORD, 2 ],
        [ 418, "Gladius", HAND, SPEAR, 3 ],
        [ 419, "Cutlass", HAND, SWORD, 1 ],
        [ 420, "Scythe", HAND, SPEAR, 7 ],
        [ 421, "Reaper's Scythe", HAND, SPEAR, 10 ],
        [ 422, "Spike", HAND, DAGGER, 6 ],
        [ 423, "Stiletto", HAND, DAGGER, 5 ],
        [ 424, "Dagger", HAND, DAGGER, 7 ],
        [ 425, "Kama", HAND, DAGGER, 8 ],
        [ 426, "Legendary Sword", HAND, SWORD, 9 ],
        [ 429, "Reaper's Crossbow", HAND, BOW, 8 ],
        [ 431, "Throwing Javelins", HAND, BOW, 2 ],
        [ 432, "Spear", HAND, SPEAR, 1 ],
        [ 433, "Hurling Javelins", HAND, BOW, 6 ],
        [ 435, "Pike", HAND, SPEAR, 7 ],
        [ 436, "Bone Staff", HAND, MAGIC, 7 ],
        [ 437, "Pronged Staff", HAND, MAGIC, 8 ],
        [ 438, "Crescent Staff", HAND, MAGIC, 4 ],
        [ 439, "Gnarled Staff", HAND, MAGIC, 5 ],
        [ 440, "Crooked Staff", HAND, MAGIC, 6 ],
        [ 441, "Shepherd's Staff", HAND, MAGIC, 7 ],
        [ 442, "Quartz Staff", HAND, MAGIC, 3 ],
        [ 443, "Eye of Soruda", HAND, MAGIC, 10 ],
        [ 444, "Skull Staff", HAND, MAGIC, 2 ],
        [ 445, "Rusty Dagger", HAND, DAGGER, 3 ],
//        [ 447, "Sword", HAND, SWORD, 1 ],
        [ 448, "Rusty Sword", HAND, SWORD, 1 ],
        [ 449, "Black Sword", HAND, SWORD, 2 ],
        [ 450, "Serrated Blade", HAND, SWORD, 4 ],
        [ 451, "Flamberge", HAND, SWORD, 6 ],
        [ 452, "Impractical Sword", HAND, SWORD, 5 ],
        [ 453, "Kris", HAND, DAGGER, 5 ],
        [ 454, "Pronged Sword", HAND, SWORD, 5 ],
        [ 455, "Shocking Sword", HAND, SWORD, 7 ],
        [ 456, "War Trident", HAND, SPEAR, 8 ],
        [ 458, "Amethyst Trident", HAND, SPEAR, 9 ],
        [ 459, "Shocking Trident", HAND, SPEAR, 10 ],
        [ 461, "Bastard Sword", HAND, SWORD, 6 ],
        [ 462, "Black Javelins", HAND, BOW, 8 ],
        [ 463, "Steel Axe", HAND, AXE, 2 ],
        [ 464, "Rat's Tail", HAND, DAGGER, 4 ],

        [ 528, "Voodoo Mask", HEAD, ARCANE, 10 ],
        [ 530, "Blue Headband", HEAD, NONE, 2 ],
        [ 532, "Red Headband", HEAD, NONE, 2 ],
        [ 533, "White Headband", HEAD, NONE, 2 ],
        [ 534, "Gold Tiara", HEAD, NONE, 3 ],
        [ 535, "Chaotic Helm", HEAD, HEAVY, 5 ],
        [ 536, "Dark Helm", HEAD, HEAVY, 7 ],
        [ 537, "Winged Helm", HEAD, NONE, 2 ],
        [ 538, "Leather Cap", HEAD, LIGHT, 2 ],
        [ 539, "Hood", HEAD, NONE, 3 ],
        [ 540, "Baseball Cap", HEAD, NONE, 1 ],
        [ 542, "Rusty Helm", HEAD, HEAVY, 1 ],
        [ 543, "Jester's Cap", HEAD, NONE, 4 ],
        [ 544, "Enchanter's Hat", HEAD, ARCANE, 5 ],
        [ 545, "Potato Sack", HEAD, NONE, 2 ],
        [ 553, "Visored Helm", HEAD, HEAVY, 3 ],
        [ 554, "Chief's Helm", HEAD, HEAVY, 4 ],
        [ 555, "Horned Helm", HEAD, HEAVY, 5 ],
        [ 556, "Bucket Helm", HEAD, HEAVY, 6 ],
        [ 557, "Banded Helm", HEAD, HEAVY, 7 ],
        [ 558, "Summoner's Hat", HEAD, ARCANE, 2 ],
        [ 559, "Bowler Hat", HEAD, NONE, 4 ],
        [ 560, "Turban", HEAD, NONE, 6 ],
        [ 561, "Bat Leather Cap", HEAD, LIGHT, 6 ],
        [ 562, "Dragon Leather Cap", HEAD, LIGHT, 8 ],
        [ 563, "Feathered Helm", HEAD, HEAVY, 3 ],
        [ 564, "Light Helm", HEAD, LIGHT, 2 ],
        [ 576, "Winged Cap", HEAD, LIGHT, 10 ],
        [ 577, "Visage of the Slayer", HEAD, HEAVY, 10 ],
        [ 578, "Knight's Helm", HEAD, HEAVY, 8 ],
        [ 579, "Cap", HEAD, LIGHT, 1 ],
        [ 580, "Helm", HEAD, HEAVY, 1 ],
        [ 582, "Rusty Helm", HEAD, HEAVY, 2 ],
        [ 583, "Gladiator's Helm", HEAD, LIGHT, 8 ],
        [ 584, "Pharoah's Mask", HEAD, ARCANE, 7 ],
        [ 585, "Ninja's Hood", HEAD, LIGHT, 5 ],
        [ 586, "Fedora", HEAD, NONE, 4 ],
        [ 587, "Bicycle Helmet", HEAD, LIGHT, 3 ],
        [ 594, "Witch's Hat", HEAD, ARCANE, 4 ],
        [ 595, "Matron Witch's Hat", HEAD, ARCANE, 6 ],
        [ 596, "Swirling Hat", HEAD, ARCANE, 8 ],
        [ 597, "Gnome's Hat", HEAD, ARCANE, 6 ],
        [ 598, "Hat of Earth", HEAD, ARCANE, 2 ],
        [ 599, "Hat of Nature", HEAD, ARCANE, 3 ],
        [ 600, "Hat of Water", HEAD, ARCANE, 4 ],
        [ 601, "Hat of Fire", HEAD, ARCANE, 5 ],
        [ 602, "Hat of Air", HEAD, ARCANE, 6 ],
        [ 603, "Horned Cap", HEAD, LIGHT, 5 ],

        [ 604, "Kilt", LEGS, NONE, 1 ],
        [ 605, "Bronze Kilt", LEGS, LIGHT, 2 ],
        [ 606, "Red Undies", LEGS, NONE, 1 ],
        [ 607, "Enchanter's Bottoms", LEGS, ARCANE, 10 ],
        [ 608, "Garters", LEGS, NONE, 3 ],
        [ 609, "Bronze Leggings", LEGS, HEAVY, 3 ],
        [ 610, "Steel Leggings", LEGS, HEAVY, 5 ],
        [ 611, "Chainmail Leggings", LEGS, LIGHT, 5 ],
        [ 614, "Emerald Leggings", LEGS, HEAVY, 10 ],
        [ 615, "Loincloth", LEGS, NONE, 2 ],
        [ 616, "Dervish Pants", LEGS, NONE, 4 ],
        [ 620, "Bat Leather Pants", LEGS, LIGHT, 8 ],
        [ 621, "Blue Jeans", LEGS, LIGHT, 6 ],
        [ 622, "Leather Pants", LEGS, LIGHT, 4 ],
        [ 623, "Drake Leather Pants", LEGS, LIGHT, 10 ],
        [ 624, "White Trousers", LEGS, NONE, 1 ],
        [ 625, "Shorts", LEGS, NONE, 2 ],
        [ 626, "Punjabi Pants", LEGS, NONE, 3 ],
        [ 630, "Black Shorts", LEGS, NONE, 5 ],
        [ 632, "Blue Dress", LEGS, NONE, 5 ],
        [ 633, "Green Dress", LEGS, NONE, 6 ],
        [ 634, "Red Dress", LEGS, NONE, 4 ],
        [ 635, "Tutu", LEGS, NONE, 3 ],
        [ 636, "Viper Dress", LEGS, NONE, 4 ],
        [ 637, "Arcane Bottoms", LEGS, ARCANE, 6 ],

        [ 249, "Black cloak", BACK, NONE, 2 ],
        [ 250, "Blue cloak", BACK, NONE, 2 ],
        [ 252, "Cyan cloak", BACK, NONE, 2 ],
        [ 254, "Green cloak", BACK, NONE, 2 ],
        [ 255, "Pink cloak", BACK, NONE, 2 ],
        [ 256, "Red cloak", BACK, NONE, 2 ],
        [ 257, "White cloak", BACK, NONE, 2 ],
        [ 258, "Yellow cloak", BACK, NONE, 2 ],
    ];

    /** A list of item IDs sorted ascending by power. */
    public static var SORTED_GOODIES :Array = TABLE.sortOn(
        "4", Array.NUMERIC | Array.RETURNINDEXEDARRAY);

    /** Returns a random item with around this power. */
    protected static function randomItem (power :int) :int
    {
        function search (low :int, high :int) :int {
            var mid :int = (low+high)/2;
            var value :int = TABLE[SORTED_GOODIES[mid]][4];

            if (high == low) {
                if (value > power) {
                    return Math.max(0, high-1);
                } else {
                    return Math.min(high+1, SORTED_GOODIES.length-1);
                }
            }

            if (value > power) {
                return search(low, mid);
            } else if (value < power) {
                return search(mid+1, high);
            } else {
                trace("Found it: " + mid); 
                return mid;
            }
        }

        var found :int = search(0, SORTED_GOODIES.length-1);
        var power :int = TABLE[SORTED_GOODIES[found]][4];

        return RandomUtil.pickRandom(SORTED_GOODIES.filter(function (item :int, ..._) :Boolean {
            return TABLE[item][4] == power;
        })) as int;
    }

    public static function randomLoot (base :Number, spread :Number) :int
    {
        var r :Number = (2*Math.random()-1);
        var power :Number =  spread*r*r*r + base;

        trace("Random power: " + power + "(r="+r+")");

        return randomItem(Math.round(power));
    }
}

}
