package bingo.client {

public class ClientBingoItems
{
    public static const ITEMS :Array = [

        new ClientBingoItem("Pearls", ["jewelry", "necklace", "beaded", "white", ], Resources.IMG_PEARLS),
        new ClientBingoItem("choker", ["jewelry", "necklace", "gem", "pink", "black", ], Resources.IMG_CHOKER),
        new ClientBingoItem("diamond necklace", ["jewelry", "necklace", "gem", "blue", ], Resources.IMG_DIAMONDNECKLACE),
        new ClientBingoItem("brown shell necklace", ["jewelry", "necklace", "shell", "brown", ], Resources.IMG_SHELLNECKLACEBROWN),
        new ClientBingoItem("blue shell necklace", ["jewelry", "necklace", "shell", "blue", ], Resources.IMG_SHELLNECKLACEBLUE),
        new ClientBingoItem("gold locket", ["jewelry", "necklace", "locket", "gold", ], Resources.IMG_LOCKETGOLD),
        new ClientBingoItem("silver locket", ["jewelry", "necklace", "locket", "silver", ], Resources.IMG_LOCKETSILVER),
        new ClientBingoItem("yellow pendant", ["jewelry", "necklace", "pendant", "yellow", "gold", "gem", ], Resources.IMG_GOLDPENDANTYELLOW),
        new ClientBingoItem("green pendant", ["jewelry", "necklace", "pendant", "green", "gold", "gem", ], Resources.IMG_GOLDPENDANTGREEN),
        new ClientBingoItem("orange pendant", ["jewelry", "necklace", "pendant", "orange", "gold", "gem", ], Resources.IMG_GOLDPENDANTORANGE),
        new ClientBingoItem("blue pendant", ["jewelry", "necklace", "pendant", "blue", "gold", "gem", ], Resources.IMG_GOLDPENDANTBLUE),
        new ClientBingoItem("purple pendant", ["jewelry", "necklace", "pendant", "purple", "gold", "gem", ], Resources.IMG_GOLDPENDANTPURPLE),
        new ClientBingoItem("pink pendant", ["jewelry", "necklace", "pendant", "pink", "gold", "gem", ], Resources.IMG_GOLDPENDANTPINK),
        new ClientBingoItem("red pendant", ["jewelry", "necklace", "pendant", "red", "gold", "gem", ], Resources.IMG_GOLDPENDANTRED),
        new ClientBingoItem("white pendant", ["jewelry", "necklace", "pendant", "white", "gold", "gem", ], Resources.IMG_GOLDPENDANTWHITE),
        new ClientBingoItem("black pendant", ["jewelry", "necklace", "pendant", "black", "gold", "gem", ], Resources.IMG_GOLDPENDANTBLACK),
        new ClientBingoItem("pearl earrings", ["head", "jewelry", "earrings", "beaded", "white", ], Resources.IMG_PEARLEARRINGS),
        new ClientBingoItem("dangly earrings", ["head", "jewelry", "earrings", "dangly", "pink", ], Resources.IMG_DANGLYEARRINGSPINK),
        new ClientBingoItem("dangly earrings", ["head", "jewelry", "earrings", "dangly", "green", ], Resources.IMG_DANGLYEARRINGSGREEN),
        new ClientBingoItem("chandalier earrings", ["head", "jewelry", "earrings", "dangly", "pink", "gold", ], Resources.IMG_CHANDALIEREARRINGS),
        new ClientBingoItem("gold diamond ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ], Resources.IMG_GOLDRINGDIAMOND),
        new ClientBingoItem("gold ruby ring", ["hands", "jewelry", "ring", "gold", "gem", "red", ], Resources.IMG_GOLDRINGRUBY),
        new ClientBingoItem("gold sapphire ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ], Resources.IMG_GOLDRINGSAPPHIRE),
        new ClientBingoItem("gold emerald ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ], Resources.IMG_GOLDRINGEMERALD),
        new ClientBingoItem("gold peridot ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ], Resources.IMG_GOLDRINGPERIDOT),
        new ClientBingoItem("silver diamond ring", ["hands", "jewelry", "ring", "silver", "gem", "blue", ], Resources.IMG_SILVERRINGDIAMOND),
        new ClientBingoItem("silver amethyst ring", ["hands", "jewelry", "ring", "silver", "gem", "purple", ], Resources.IMG_SILVERRINGAMETHYST),
        new ClientBingoItem("silver zircon ring", ["hands", "jewelry", "ring", "silver", "gem", "pink", ], Resources.IMG_SILVERRINGPINK),
        new ClientBingoItem("silver garnet ring", ["hands", "jewelry", "ring", "silver", "gem", "orange", ], Resources.IMG_SILVERRINGORANGE),
        new ClientBingoItem("red/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "red", ], Resources.IMG_CLASSRINGRED),
        new ClientBingoItem("purple/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "purple", ], Resources.IMG_CLASSRINGPURPLE),
        new ClientBingoItem("blue/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ], Resources.IMG_CLASSRINGBLUE),
        new ClientBingoItem("green/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ], Resources.IMG_CLASSRINGGREEN),
        new ClientBingoItem("red/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "red", ], Resources.IMG_CLASSRINGSILVERRED),
        new ClientBingoItem("purple/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "purple", ], Resources.IMG_CLASSRINGSILVERPURPLE),
        new ClientBingoItem("blue/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "blue", ], Resources.IMG_CLASSRINGSILVERBLUE),
        new ClientBingoItem("green/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "green", ], Resources.IMG_CLASSRINGSILVERGREEN),
        new ClientBingoItem("patterned heel 1", ["feet", "shoes", "heel", "pattern", "brown", "animal", ], Resources.IMG_HEELPATTERN01),
        new ClientBingoItem("patterned heel 2", ["feet", "shoes", "heel", "pattern", "green", "polka-dot", ], Resources.IMG_HEELPATTERN02),
        new ClientBingoItem("patterned heel 3", ["feet", "shoes", "heel", "pattern", "blue", "black", ], Resources.IMG_HEELPATTERN03),
        new ClientBingoItem("patterned heel 4", ["feet", "shoes", "heel", "pattern", "white", "polka-dot", ], Resources.IMG_HEELPATTERN04),
        new ClientBingoItem("patterned heel 5", ["feet", "shoes", "heel", "pattern", "pink", "purple", "orange", "brown", ], Resources.IMG_HEELPATTERN05),
        new ClientBingoItem("short brown boot", ["feet", "shoes", "boot", "brown", "orange", "winter", "heel", ], Resources.IMG_SHORTBOOTBROWN),
        new ClientBingoItem("short pink boot", ["feet", "shoes", "boot", "pink", "winter", "heel", ], Resources.IMG_SHORTBOOTPINK),
        new ClientBingoItem("short blue boot", ["feet", "shoes", "boot", "blue", "winter", "heel", ], Resources.IMG_SHORTBOOTBLUE),
        new ClientBingoItem("short black boot", ["feet", "shoes", "boot", "black", "winter", "heel", ], Resources.IMG_SHORTBOOTBLACK),
        new ClientBingoItem("red boot", ["feet", "shoes", "boot", "red", "winter", "heel", ], Resources.IMG_TALLBOOTRED),
        new ClientBingoItem("black boot", ["feet", "shoes", "boot", "black", "winter", "heel", ], Resources.IMG_TALLBOOTBLACK),
        new ClientBingoItem("brown boot", ["feet", "shoes", "boot", "brown", "orange", "winter", "heel", ], Resources.IMG_TALLBOOTBROWN),
        new ClientBingoItem("green boot", ["feet", "shoes", "boot", "green", "winter", "heel", ], Resources.IMG_TALLBOOTGREEN),
        new ClientBingoItem("purple boot", ["feet", "shoes", "boot", "purple", "winter", "heel", ], Resources.IMG_TALLBOOTPURPLE),
        new ClientBingoItem("silver boot", ["feet", "shoes", "boot", "silver", "winter", "heel", ], Resources.IMG_TALLBOOTSILVER),
        new ClientBingoItem("pink fuzzy slipper", ["feet", "shoes", "flats", "pink", ], Resources.IMG_FUZZYSLIPPERPINK),
        new ClientBingoItem("blue fuzzy slipper", ["feet", "shoes", "flats", "blue", ], Resources.IMG_FUZZYSLIPPERBLUE),
        new ClientBingoItem("red fuzzy slipper", ["feet", "shoes", "flats", "red", ], Resources.IMG_FUZZYSLIPPERRED),
        new ClientBingoItem("yellow fuzzy slipper", ["feet", "shoes", "flats", "yellow", ], Resources.IMG_FUZZYSLIPPERYELLOW),
        new ClientBingoItem("black wedge", ["feet", "shoes", "wedge", "black", ], Resources.IMG_WEDGEBLACK),
        new ClientBingoItem("green wedge", ["feet", "shoes", "wedge", "green", ], Resources.IMG_WEDGEGREEN),
        new ClientBingoItem("red wedge", ["feet", "shoes", "wedge", "red", ], Resources.IMG_WEDGERED),
        new ClientBingoItem("blue wedge", ["feet", "shoes", "wedge", "blue", ], Resources.IMG_WEDGEBLUE),
        new ClientBingoItem("black sandal", ["feet", "shoes", "flats", "black", "brown", "summer", ], Resources.IMG_SANDALBLACK),
        new ClientBingoItem("blue sandal", ["feet", "shoes", "flats", "blue", "brown", "summer", ], Resources.IMG_SANDALBLUE),
        new ClientBingoItem("orange sandal", ["feet", "shoes", "flats", "orange", "brown", "summer", ], Resources.IMG_SANDALORANGE),
        new ClientBingoItem("purple sandal", ["feet", "shoes", "flats", "purple", "brown", "summer", ], Resources.IMG_SANDALPURPLE),
        new ClientBingoItem("red sandal", ["feet", "shoes", "flats", "red", "brown", "summer", ], Resources.IMG_SANDALRED),
        new ClientBingoItem("green sandal", ["feet", "shoes", "flats", "green", "brown", "summer", ], Resources.IMG_SANDALSGREEN),
        new ClientBingoItem("pink sandal", ["feet", "shoes", "flats", "pink", "brown", "summer", ], Resources.IMG_SANDALSPINK),
        new ClientBingoItem("yellow sandal", ["feet", "shoes", "flats", "yellow", "brown", "summer", ], Resources.IMG_SANDALSYELLOW),
        new ClientBingoItem("red flat", ["feet", "shoes", "flats", "red", "summer", ], Resources.IMG_FLATSRED),
        new ClientBingoItem("pink flat", ["feet", "shoes", "flats", "pink", "summer", ], Resources.IMG_FLATSPINK),
        new ClientBingoItem("purple flat", ["feet", "shoes", "flats", "purple", "summer", ], Resources.IMG_FLATSPURPLE),
        new ClientBingoItem("blue flat", ["feet", "shoes", "flats", "blue", "summer", ], Resources.IMG_FLATSBLUE),
        new ClientBingoItem("orange flat", ["feet", "shoes", "flats", "orange", "summer", ], Resources.IMG_FLATSORANGE),
        new ClientBingoItem("green flat", ["feet", "shoes", "flats", "green", "summer", ], Resources.IMG_FLATSGREEN),
        new ClientBingoItem("yellow flat", ["feet", "shoes", "flats", "yellow", "summer", ], Resources.IMG_FLATSYELLOW),
        new ClientBingoItem("patterned flat 1", ["feet", "shoes", "flats", "pattern", "summer", "green", "floral", ], Resources.IMG_FLATSPATTERN01),
        new ClientBingoItem("patterned flat 2", ["feet", "shoes", "flats", "pattern", "summer", "red", "orange", ], Resources.IMG_FLATSPATTERN02),
        new ClientBingoItem("patterned flat 3", ["feet", "shoes", "flats", "pattern", "summer", "stripes", "animal", "black", "white", ], Resources.IMG_FLATSPATTERN03),
        new ClientBingoItem("patterned flat 4", ["feet", "shoes", "flats", "pattern", "summer", "plaid", ], Resources.IMG_FLATSPATTERN04),
        new ClientBingoItem("patterned flat 5", ["feet", "shoes", "flats", "pattern", "summer", "white", "polka-dot", ], Resources.IMG_FLATSPATTERN05),
        new ClientBingoItem("patterned flat 6", ["feet", "shoes", "flats", "pattern", "summer", "red", "floral", ], Resources.IMG_FLATSPATTERN06),
        new ClientBingoItem("patterned flat 7", ["feet", "shoes", "flats", "pattern", "summer", "brown", "animal", ], Resources.IMG_FLATSPATTERN07),
        new ClientBingoItem("blue sneakers", ["feet", "shoes", "flats", "blue", "white", "stripes", ], Resources.IMG_SNEAKERSBLUE),
        new ClientBingoItem("green sneakers", ["feet", "shoes", "flats", "green", "white", "stripes", ], Resources.IMG_SNEAKERSGREEN),
        new ClientBingoItem("orange sneakers", ["feet", "shoes", "flats", "orange", "white", "stripes", ], Resources.IMG_SNEAKERSORANGE),
        new ClientBingoItem("pink sneakers", ["feet", "shoes", "flats", "pink", "white", "stripes", ], Resources.IMG_SNEAKERSPINK),
        new ClientBingoItem("purple sneakers", ["feet", "shoes", "flats", "purple", "white", "stripes", ], Resources.IMG_SNEAKERSPURPLE),
        new ClientBingoItem("red sneakers", ["feet", "shoes", "flats", "red", "white", "stripes", ], Resources.IMG_SNEAKERSRED),
        new ClientBingoItem("yellow sneakers", ["feet", "shoes", "flats", "white", "yellow", "stripes", ], Resources.IMG_SNEAKERSYELLOW),
        new ClientBingoItem("bobby pins", ["head", "hair", "gem", "beaded", "silver", "blue", ], Resources.IMG_BOBBYPINS),
        new ClientBingoItem("patterned barrette 1", ["head", "hair", "pattern", "red", ], Resources.IMG_BARRETTEPATTERN01),
        new ClientBingoItem("patterned barrette 2", ["head", "hair", "pattern", "blue", ], Resources.IMG_BARRETTEPATTERN02),
        new ClientBingoItem("patterned barrette 3", ["head", "hair", "pattern", "orange", "yellow", ], Resources.IMG_BARRETTEPATTERN03),
        new ClientBingoItem("black headband", ["head", "hair", "black", ], Resources.IMG_HEADBANDBLACK),
        new ClientBingoItem("blue headband", ["head", "hair", "blue", ], Resources.IMG_HEADBANDBLUE),
        new ClientBingoItem("green headband", ["head", "hair", "green", ], Resources.IMG_HEADBANDGREEN),
        new ClientBingoItem("orange headband", ["head", "hair", "orange", ], Resources.IMG_HEADBANDORANGE),
        new ClientBingoItem("pink headband", ["head", "hair", "pink", ], Resources.IMG_HEADBANDPINK),
        new ClientBingoItem("purple headband", ["head", "hair", "purple", ], Resources.IMG_HEADBANDPURPLE),
        new ClientBingoItem("red headband", ["head", "hair", "red", ], Resources.IMG_HEADBANDRED),
        new ClientBingoItem("yellow headband", ["head", "hair", "yellow", ], Resources.IMG_HEADBANDYELLOW),
        new ClientBingoItem("red double headband", ["head", "hair", "red", ], Resources.IMG_DOUBLEHEADBANDRED),
        new ClientBingoItem("pink double headband", ["head", "hair", "pink", ], Resources.IMG_DOUBLEHEADBANDPINK),
        new ClientBingoItem("purple double headband", ["head", "hair", "purple", ], Resources.IMG_DOUBLEHEADBANDPURPLE),
        new ClientBingoItem("blue double headband", ["head", "hair", "blue", ], Resources.IMG_DOUBLEHEADBANDBLUE),
        new ClientBingoItem("orange double headband", ["head", "hair", "orange", ], Resources.IMG_DOUBLEHEADBANDORANGE),
        new ClientBingoItem("green double headband", ["head", "hair", "green", ], Resources.IMG_DOUBLEHEADBANDGREEN),
        new ClientBingoItem("yellow double headband", ["head", "hair", "yellow", ], Resources.IMG_DOUBLEHEADBANDYELLOW),
        new ClientBingoItem("black double headband", ["head", "hair", "black", ], Resources.IMG_DOUBLEHEADBANDBLACK),
        new ClientBingoItem("fabric headband 1", ["head", "hair", "pattern", "green", "floral", ], Resources.IMG_FABRICHEADBAND01),
        new ClientBingoItem("fabric headband 2", ["head", "hair", "pattern", "stripes", "animal", "black", "white", ], Resources.IMG_FABRICHEADBAND02),
        new ClientBingoItem("fabric headband 3", ["head", "hair", "pattern", "green", "plaid", ], Resources.IMG_FABRICHEADBAND03),
        new ClientBingoItem("fabric headband 4", ["head", "hair", "pattern", "brown", "polka-dot", ], Resources.IMG_FABRICHEADBAND04),
        new ClientBingoItem("fabric headband 5", ["head", "hair", "pattern", "pink", "floral", ], Resources.IMG_FABRICHEADBAND05),
        new ClientBingoItem("fabric headband 6", ["head", "hair", "pattern", "white", "polka-dot", ], Resources.IMG_FABRICHEADBAND06),
        new ClientBingoItem("fabric headband 7", ["head", "hair", "pattern", "red", "orange", "floral", ], Resources.IMG_FABRICHEADBAND07),
        new ClientBingoItem("fabric headband 8", ["head", "hair", "pattern", "red", "plaid", ], Resources.IMG_FABRICHEADBAND08),
        new ClientBingoItem("fabric headband 9", ["head", "hair", "pattern", "blue", "floral", ], Resources.IMG_FABRICHEADBAND09),
        new ClientBingoItem("fabric headband 10", ["head", "hair", "pattern", "floral", ], Resources.IMG_FABRICHEADBAND10),
        new ClientBingoItem("fabric headband 11", ["head", "hair", "pattern", "brown", "animal", ], Resources.IMG_FABRICHEADBAND11),
        new ClientBingoItem("fabric headband 12", ["head", "hair", "pattern", "pink", "floral", ], Resources.IMG_FABRICHEADBAND12),
        new ClientBingoItem("fabric headband 13", ["head", "hair", "pattern", "green", "floral", ], Resources.IMG_FABRICHEADBAND13),
        new ClientBingoItem("fabric headband 14", ["head", "hair", "pattern", "red", "orange", "brown", "floral", ], Resources.IMG_FABRICHEADBAND14),
        new ClientBingoItem("fabric headband 15", ["head", "hair", "pattern", "yellow", "animal", ], Resources.IMG_FABRICHEADBAND15),
        new ClientBingoItem("fabric headband 16", ["head", "hair", "pattern", "white", "floral", ], Resources.IMG_FABRICHEADBAND16),
        new ClientBingoItem("fabric headband 17", ["head", "hair", "pattern", "green", "polka-dot", ], Resources.IMG_FABRICHEADBAND17),
        new ClientBingoItem("black bow clips", ["head", "hair", "black", "bow", ], Resources.IMG_BOWCLIPSBLACK),
        new ClientBingoItem("blue bow clips", ["head", "hair", "blue", "bow", ], Resources.IMG_BOWCLIPSBLUE),
        new ClientBingoItem("green bow clips", ["head", "hair", "green", "bow", ], Resources.IMG_BOWCLIPSGREEN),
        new ClientBingoItem("orange bow clips", ["head", "hair", "orange", "bow", ], Resources.IMG_BOWCLIPSORANGE),
        new ClientBingoItem("pink bow clips", ["head", "hair", "pink", "bow", ], Resources.IMG_BOWCLIPSPINK),
        new ClientBingoItem("purple bow clips", ["head", "hair", "purple", "bow", ], Resources.IMG_BOWCLIPSPURPLE),
        new ClientBingoItem("red bow clips", ["head", "hair", "red", "bow", ], Resources.IMG_BOWCLIPSRED),
        new ClientBingoItem("white bow clips", ["head", "hair", "white", "bow", ], Resources.IMG_BOWCLIPSWHITE),
        new ClientBingoItem("yellow bow clips", ["head", "hair", "yellow", "bow", ], Resources.IMG_BOWCLIPSYELLOW),
        new ClientBingoItem("patterned bow clips 1", ["head", "hair", "pattern", "bow", "pink", ], Resources.IMG_BOWCLIPSPATTERN01),
        new ClientBingoItem("patterned bow clips 2", ["head", "hair", "pattern", "bow", "red", ], Resources.IMG_BOWCLIPSPATTERN02),
        new ClientBingoItem("patterned bow clips 3", ["head", "hair", "pattern", "bow", "blue", ], Resources.IMG_BOWCLIPSPATTERN03),
        new ClientBingoItem("patterned bow clips 4", ["head", "hair", "pattern", "bow", "green", ], Resources.IMG_BOWCLIPSPATTERN04),
        new ClientBingoItem("patterned bow clips 5", ["head", "hair", "pattern", "bow", "animal", ], Resources.IMG_BOWCLIPSPATTERN05),
        new ClientBingoItem("brown claw", ["head", "hair", "brown", ], Resources.IMG_CLAWBROWN),
        new ClientBingoItem("black claw", ["head", "hair", "black", ], Resources.IMG_CLAWBLACK),
        new ClientBingoItem("red claw", ["head", "hair", "red", ], Resources.IMG_CLAWRED),
        new ClientBingoItem("pink claw", ["head", "hair", "pink", ], Resources.IMG_CLAWPINK),
        new ClientBingoItem("purple claw", ["head", "hair", "purple", ], Resources.IMG_CLAWPURPLE),
        new ClientBingoItem("blue claw", ["head", "hair", "blue", ], Resources.IMG_CLAWBLUE),
        new ClientBingoItem("orange claw", ["head", "hair", "orange", ], Resources.IMG_CLAWORANGE),
        new ClientBingoItem("green claw", ["head", "hair", "green", ], Resources.IMG_CLAWGREEN),
        new ClientBingoItem("yellow claw", ["head", "hair", "yellow", ], Resources.IMG_CLAWYELLOW),
        new ClientBingoItem("red baret", ["head", "hat", "red", ], Resources.IMG_BARET),
        new ClientBingoItem("purple baret", ["head", "hat", "purple", ], Resources.IMG_BARETPURPLE),
        new ClientBingoItem("orange baseball cap", ["head", "hat", "orange", "brown", ], Resources.IMG_BASEBALLCAP),
        new ClientBingoItem("blue baseball cap", ["head", "hat", "blue", ], Resources.IMG_BASEBALLCAPBLUE),
        new ClientBingoItem("green baseball cap", ["head", "hat", "green", ], Resources.IMG_BASEBALLCAPGREEN),
        new ClientBingoItem("black cowboy hat", ["head", "hat", "red", "black", ], Resources.IMG_COWBOYHATBLACK),
        new ClientBingoItem("cowboy hat", ["head", "hat", "green", "brown", ], Resources.IMG_COWBOYHAT),
        new ClientBingoItem("'earflap' hat", ["head", "hat", "winter", "blue", ], Resources.IMG_EARFLAPHAT),
        new ClientBingoItem("brown 'earflap' hat", ["head", "hat", "winter", "brown", ], Resources.IMG_EARFLAPHATBROWN),
        new ClientBingoItem("fedora", ["head", "hat", "white", "orange", "brown", ], Resources.IMG_FEDORA),
        new ClientBingoItem("patterned fedora", ["head", "hat", "white", "black", "floral", "pattern", ], Resources.IMG_FEDORAPATTERN),
        new ClientBingoItem("newsboy hat", ["head", "hat", "blue", "floral", ], Resources.IMG_NEWSBOYHAT),
        new ClientBingoItem("patterned newsboy hat", ["head", "hat", "orange", "pink", "purple", "pattern", "floral", ], Resources.IMG_NEWSBOYHATPATTERN),
        new ClientBingoItem("blue snow cap", ["head", "hat", "winter", "blue", ], Resources.IMG_SNOWCAPBLUE),
        new ClientBingoItem("snow cap", ["head", "hat", "winter", "pink", ], Resources.IMG_SNOWCAP),
        new ClientBingoItem("straw/sun hat", ["head", "hat", "summer", "red", ], Resources.IMG_STRAWHAT),
        new ClientBingoItem("patterned straw/sun hat", ["head", "hat", "summer", "green", "pattern", "floral", ], Resources.IMG_STRAWHATPATTERN),
        new ClientBingoItem("patterned tote 1", ["bag", "tote", "pattern", "stripes", "animal", "purple", "black", "white", ], Resources.IMG_TOTEPATTERN01),
        new ClientBingoItem("patterned tote 2", ["bag", "tote", "pattern", "brown", "floral", ], Resources.IMG_TOTEPATTERN02),
        new ClientBingoItem("patterned tote 3", ["bag", "tote", "pattern", "pink", "white", "polka-dot", ], Resources.IMG_TOTEPATTERN03),
        new ClientBingoItem("patterned tote 4", ["bag", "tote", "pattern", "red", "orange", "floral", ], Resources.IMG_TOTEPATTERN04),
        new ClientBingoItem("patterned tote 5", ["bag", "tote", "pattern", "blue", "floral", ], Resources.IMG_TOTEPATTERN05),
        new ClientBingoItem("patterned tote 6", ["bag", "tote", "pattern", "green", "floral", ], Resources.IMG_TOTEPATTERN06),
        new ClientBingoItem("patterned tote 7", ["bag", "tote", "pattern", "brown", "animal", ], Resources.IMG_TOTEPATTERN07),
        new ClientBingoItem("patterned tote 8", ["bag", "tote", "pattern", "pink", "stripes", ], Resources.IMG_TOTEPATTERN08),
        new ClientBingoItem("patterned tote 9", ["bag", "tote", "pattern", "pink", "white", "floral", ], Resources.IMG_TOTEPATTERN09),
        new ClientBingoItem("patterned tote 10", ["bag", "tote", "pattern", "pink", "purple", "orange", "floral", ], Resources.IMG_TOTEPATTERN10),
        new ClientBingoItem("patterned tote 11", ["bag", "tote", "pattern", "yellow", "black", "animal", ], Resources.IMG_TOTEPATTERN11),
        new ClientBingoItem("patterned tote 12", ["bag", "tote", "pattern", "white", "pink", "floral", ], Resources.IMG_TOTEPATTERN12),
        new ClientBingoItem("patterned tote 13", ["bag", "tote", "pattern", "black", "white", "floral", ], Resources.IMG_TOTEPATTERN13),
        new ClientBingoItem("patterned tote 14", ["bag", "tote", "pattern", "yellow", "floral", ], Resources.IMG_TOTEPATTERN14),
        new ClientBingoItem("patterned tote 15", ["bag", "tote", "pattern", "green", "stripes", ], Resources.IMG_TOTEPATTERN15),
        new ClientBingoItem("brown woven tote", ["bag", "tote", "brown", ], Resources.IMG_WOVENTOTEBROWN),
        new ClientBingoItem("orange woven tote", ["bag", "tote", "orange", ], Resources.IMG_WOVENTOTEORANGE),
        new ClientBingoItem("yellow woven tote", ["bag", "tote", "yellow", ], Resources.IMG_WOVENTOTEYELLOW),
        new ClientBingoItem("blue change purse", ["bag", "blue", ], Resources.IMG_CHANGEPURSEBLUE),
        new ClientBingoItem("red change purse", ["bag", "red", ], Resources.IMG_CHANGEPURSERED),
        new ClientBingoItem("pink change purse", ["bag", "pink", ], Resources.IMG_CHANGEPURSEPINK),
        new ClientBingoItem("purple change purse", ["bag", "purple", ], Resources.IMG_CHANGEPURSEPURPLE),
        new ClientBingoItem("orange change purse", ["bag", "orange", ], Resources.IMG_CHANGEPURSEORANGE),
        new ClientBingoItem("green change purse", ["bag", "green", ], Resources.IMG_CHANGEPURSEGREEN),
        new ClientBingoItem("yellow change purse", ["bag", "yellow", ], Resources.IMG_CHANGEPURSEYELLOW),
        new ClientBingoItem("clutch", ["bag", "brown", "gold", ], Resources.IMG_CLUTCH),
        new ClientBingoItem("green baguette", ["bag", "green", ], Resources.IMG_BAGUETTEGREEN),
        new ClientBingoItem("purple baguette", ["bag", "purple", ], Resources.IMG_BAGUETTEPURPLE),
        new ClientBingoItem("patterned purse 1", ["bag", "pattern", "green", "polka-dot", ], Resources.IMG_PURSEPATTERN01),
        new ClientBingoItem("patterned purse 2", ["bag", "pattern", "blue", "floral", ], Resources.IMG_PURSEPATTERN02),
        new ClientBingoItem("patterned purse 3", ["bag", "pattern", "brown", "polka-dot", ], Resources.IMG_PURSEPATTERN03),
        new ClientBingoItem("patterned purse 4", ["bag", "pattern", "red", "floral", ], Resources.IMG_PURSEPATTERN04),

        // recolored items
        new ClientBingoItem("garnet gemstone earrings", ["head", "jewelry", "earrings", "gem", "red", ], Resources.IMG_GEMEARRINGS,       true, 0xCC0000, 0.51 ),
        new ClientBingoItem("purple gemstone earrings", ["head", "jewelry", "earrings", "gem", "purple", ], Resources.IMG_GEMEARRINGS,    true, 0x660066, 0.51),
        new ClientBingoItem("teal gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ], Resources.IMG_GEMEARRINGS,        true, 0x99FFFF, 0.51),
        new ClientBingoItem("silver gemstone earrings", ["head", "jewelry", "earrings", "gem", "silver", ], Resources.IMG_GEMEARRINGS,    true, 0xFFFFFF, 0.51),
        new ClientBingoItem("green gemstone earrings", ["head", "jewelry", "earrings", "gem", "green", ], Resources.IMG_GEMEARRINGS,      true, 0x006600, 0.51),
        new ClientBingoItem("ruby gemstone earrings", ["head", "jewelry", "earrings", "gem", "red", ], Resources.IMG_GEMEARRINGS,         true, 0xFF0000, 0.51),
        new ClientBingoItem("light green gemstone earrings", ["head", "jewelry", "earrings", "gem", "green", ], Resources.IMG_GEMEARRINGS, true, 0x99FF66, 0.51),
        new ClientBingoItem("blue gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ], Resources.IMG_GEMEARRINGS,        true, 0x0000FF, 0.51),
        new ClientBingoItem("pink gemstone earrings", ["head", "jewelry", "earrings", "gem", "pink", ], Resources.IMG_GEMEARRINGS,        true, 0xFF0066, 0.51),
        new ClientBingoItem("yellow gemstone earrings", ["head", "jewelry", "earrings", "gem", "yellow", ], Resources.IMG_GEMEARRINGS,    true, 0xFFFF66, 0.51),
        new ClientBingoItem("light blue gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ], Resources.IMG_GEMEARRINGS,  true, 0x0099FF, 0.51),

        new ClientBingoItem("silver hoop earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ], Resources.IMG_HOOPEARRINGS, true, 0xCCCCCC, 0.51),
        new ClientBingoItem("gold hoop earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ], Resources.IMG_HOOPEARRINGS, true, 0xCC9900, 0.51),

        new ClientBingoItem("silver thick hoop earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ], Resources.IMG_THICKHOOPEARRINGS, true, 0xCCCCCC, 0.51),
        new ClientBingoItem("gold thick hoop earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ], Resources.IMG_THICKHOOPEARRINGS, true, 0xCC9900, 0.51),

        new ClientBingoItem("silver bubble earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ], Resources.IMG_BUBBLEEARRINGS, true, 0xCCCCCC, 0.51),
        new ClientBingoItem("gold bubble earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ], Resources.IMG_BUBBLEEARRINGS, true, 0xCC9900, 0.51),

        new ClientBingoItem("silver basic ring", ["hands", "jewelry", "ring", "silver", ], Resources.IMG_BASICRING, true, 0xCCCCCC, 0.51),
        new ClientBingoItem("gold basic ring", ["hands", "jewelry", "ring", "gold", ], Resources.IMG_BASICRING, true, 0xCC9900, 0.51),

        new ClientBingoItem("red solid heel", ["feet", "shoes", "heel", "red", ], Resources.IMG_HEELSOLID, true, 0xFF0000, 0.51),
        new ClientBingoItem("pink solid heel", ["feet", "shoes", "heel", "pink", ], Resources.IMG_HEELSOLID, true, 0xFF3366, 0.51),
        new ClientBingoItem("purple solid heel", ["feet", "shoes", "heel", "purple", ], Resources.IMG_HEELSOLID, true, 0x660066, 0.51),
        new ClientBingoItem("blue solid heel", ["feet", "shoes", "heel", "blue", ], Resources.IMG_HEELSOLID, true, 0x003399, 0.51),
        new ClientBingoItem("orange solid heel", ["feet", "shoes", "heel", "orange", ], Resources.IMG_HEELSOLID, true, 0xFF6600, 0.51),
        new ClientBingoItem("green solid heel", ["feet", "shoes", "heel", "green", ], Resources.IMG_HEELSOLID, true, 0x006633, 0.51),
        new ClientBingoItem("yellow solid heel", ["feet", "shoes", "heel", "yellow", ], Resources.IMG_HEELSOLID, true, 0xFFCC00, 0.51),
        new ClientBingoItem("black solid heel", ["feet", "shoes", "heel", "black", ], Resources.IMG_HEELSOLID, true, 0x000000, 0.56),

    ];
}

}
