package bingo.server {

import bingo.BingoItem;

public class ServerBingoItems
{
    public static const ITEMS :Array = [

        new BingoItem("Pearls", ["jewelry", "necklace", "beaded", "white", ]),
        new BingoItem("choker", ["jewelry", "necklace", "gem", "pink", "black", ]),
        new BingoItem("diamond necklace", ["jewelry", "necklace", "gem", "blue", ]),
        new BingoItem("brown shell necklace", ["jewelry", "necklace", "shell", "brown", ]),
        new BingoItem("blue shell necklace", ["jewelry", "necklace", "shell", "blue", ]),
        new BingoItem("gold locket", ["jewelry", "necklace", "locket", "gold", ]),
        new BingoItem("silver locket", ["jewelry", "necklace", "locket", "silver", ]),
        new BingoItem("yellow pendant", ["jewelry", "necklace", "pendant", "yellow", "gold", "gem", ]),
        new BingoItem("green pendant", ["jewelry", "necklace", "pendant", "green", "gold", "gem", ]),
        new BingoItem("orange pendant", ["jewelry", "necklace", "pendant", "orange", "gold", "gem", ]),
        new BingoItem("blue pendant", ["jewelry", "necklace", "pendant", "blue", "gold", "gem", ]),
        new BingoItem("purple pendant", ["jewelry", "necklace", "pendant", "purple", "gold", "gem", ]),
        new BingoItem("pink pendant", ["jewelry", "necklace", "pendant", "pink", "gold", "gem", ]),
        new BingoItem("red pendant", ["jewelry", "necklace", "pendant", "red", "gold", "gem", ]),
        new BingoItem("white pendant", ["jewelry", "necklace", "pendant", "white", "gold", "gem", ]),
        new BingoItem("black pendant", ["jewelry", "necklace", "pendant", "black", "gold", "gem", ]),
        new BingoItem("pearl earrings", ["head", "jewelry", "earrings", "beaded", "white", ]),
        new BingoItem("dangly earrings", ["head", "jewelry", "earrings", "dangly", "pink", ]),
        new BingoItem("dangly earrings", ["head", "jewelry", "earrings", "dangly", "green", ]),
        new BingoItem("chandalier earrings", ["head", "jewelry", "earrings", "dangly", "pink", "gold", ]),
        new BingoItem("gold diamond ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ]),
        new BingoItem("gold ruby ring", ["hands", "jewelry", "ring", "gold", "gem", "red", ]),
        new BingoItem("gold sapphire ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ]),
        new BingoItem("gold emerald ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ]),
        new BingoItem("gold peridot ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ]),
        new BingoItem("silver diamond ring", ["hands", "jewelry", "ring", "silver", "gem", "blue", ]),
        new BingoItem("silver amethyst ring", ["hands", "jewelry", "ring", "silver", "gem", "purple", ]),
        new BingoItem("silver zircon ring", ["hands", "jewelry", "ring", "silver", "gem", "pink", ]),
        new BingoItem("silver garnet ring", ["hands", "jewelry", "ring", "silver", "gem", "orange", ]),
        new BingoItem("red/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "red", ]),
        new BingoItem("purple/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "purple", ]),
        new BingoItem("blue/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "blue", ]),
        new BingoItem("green/gold class ring", ["hands", "jewelry", "ring", "gold", "gem", "green", ]),
        new BingoItem("red/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "red", ]),
        new BingoItem("purple/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "purple", ]),
        new BingoItem("blue/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "blue", ]),
        new BingoItem("green/silver class ring", ["hands", "jewelry", "ring", "silver", "gem", "green", ]),
        new BingoItem("patterned heel 1", ["feet", "shoes", "heel", "pattern", "brown", "animal", ]),
        new BingoItem("patterned heel 2", ["feet", "shoes", "heel", "pattern", "green", "polka-dot", ]),
        new BingoItem("patterned heel 3", ["feet", "shoes", "heel", "pattern", "blue", "black", ]),
        new BingoItem("patterned heel 4", ["feet", "shoes", "heel", "pattern", "white", "polka-dot", ]),
        new BingoItem("patterned heel 5", ["feet", "shoes", "heel", "pattern", "pink", "purple", "orange", "brown", ]),
        new BingoItem("short brown boot", ["feet", "shoes", "boot", "brown", "orange", "winter", "heel", ]),
        new BingoItem("short pink boot", ["feet", "shoes", "boot", "pink", "winter", "heel", ]),
        new BingoItem("short blue boot", ["feet", "shoes", "boot", "blue", "winter", "heel", ]),
        new BingoItem("short black boot", ["feet", "shoes", "boot", "black", "winter", "heel", ]),
        new BingoItem("red boot", ["feet", "shoes", "boot", "red", "winter", "heel", ]),
        new BingoItem("black boot", ["feet", "shoes", "boot", "black", "winter", "heel", ]),
        new BingoItem("brown boot", ["feet", "shoes", "boot", "brown", "orange", "winter", "heel", ]),
        new BingoItem("green boot", ["feet", "shoes", "boot", "green", "winter", "heel", ]),
        new BingoItem("purple boot", ["feet", "shoes", "boot", "purple", "winter", "heel", ]),
        new BingoItem("silver boot", ["feet", "shoes", "boot", "silver", "winter", "heel", ]),
        new BingoItem("pink fuzzy slipper", ["feet", "shoes", "flats", "pink", ]),
        new BingoItem("blue fuzzy slipper", ["feet", "shoes", "flats", "blue", ]),
        new BingoItem("red fuzzy slipper", ["feet", "shoes", "flats", "red", ]),
        new BingoItem("yellow fuzzy slipper", ["feet", "shoes", "flats", "yellow", ]),
        new BingoItem("black wedge", ["feet", "shoes", "wedge", "black", ]),
        new BingoItem("green wedge", ["feet", "shoes", "wedge", "green", ]),
        new BingoItem("red wedge", ["feet", "shoes", "wedge", "red", ]),
        new BingoItem("blue wedge", ["feet", "shoes", "wedge", "blue", ]),
        new BingoItem("black sandal", ["feet", "shoes", "flats", "black", "brown", "summer", ]),
        new BingoItem("blue sandal", ["feet", "shoes", "flats", "blue", "brown", "summer", ]),
        new BingoItem("orange sandal", ["feet", "shoes", "flats", "orange", "brown", "summer", ]),
        new BingoItem("purple sandal", ["feet", "shoes", "flats", "purple", "brown", "summer", ]),
        new BingoItem("red sandal", ["feet", "shoes", "flats", "red", "brown", "summer", ]),
        new BingoItem("green sandal", ["feet", "shoes", "flats", "green", "brown", "summer", ]),
        new BingoItem("pink sandal", ["feet", "shoes", "flats", "pink", "brown", "summer", ]),
        new BingoItem("yellow sandal", ["feet", "shoes", "flats", "yellow", "brown", "summer", ]),
        new BingoItem("red flat", ["feet", "shoes", "flats", "red", "summer", ]),
        new BingoItem("pink flat", ["feet", "shoes", "flats", "pink", "summer", ]),
        new BingoItem("purple flat", ["feet", "shoes", "flats", "purple", "summer", ]),
        new BingoItem("blue flat", ["feet", "shoes", "flats", "blue", "summer", ]),
        new BingoItem("orange flat", ["feet", "shoes", "flats", "orange", "summer", ]),
        new BingoItem("green flat", ["feet", "shoes", "flats", "green", "summer", ]),
        new BingoItem("yellow flat", ["feet", "shoes", "flats", "yellow", "summer", ]),
        new BingoItem("patterned flat 1", ["feet", "shoes", "flats", "pattern", "summer", "green", "floral", ]),
        new BingoItem("patterned flat 2", ["feet", "shoes", "flats", "pattern", "summer", "red", "orange", ]),
        new BingoItem("patterned flat 3", ["feet", "shoes", "flats", "pattern", "summer", "stripes", "animal", "black", "white", ]),
        new BingoItem("patterned flat 4", ["feet", "shoes", "flats", "pattern", "summer", "plaid", ]),
        new BingoItem("patterned flat 5", ["feet", "shoes", "flats", "pattern", "summer", "white", "polka-dot", ]),
        new BingoItem("patterned flat 6", ["feet", "shoes", "flats", "pattern", "summer", "red", "floral", ]),
        new BingoItem("patterned flat 7", ["feet", "shoes", "flats", "pattern", "summer", "brown", "animal", ]),
        new BingoItem("blue sneakers", ["feet", "shoes", "flats", "blue", "white", "stripes", ]),
        new BingoItem("green sneakers", ["feet", "shoes", "flats", "green", "white", "stripes", ]),
        new BingoItem("orange sneakers", ["feet", "shoes", "flats", "orange", "white", "stripes", ]),
        new BingoItem("pink sneakers", ["feet", "shoes", "flats", "pink", "white", "stripes", ]),
        new BingoItem("purple sneakers", ["feet", "shoes", "flats", "purple", "white", "stripes", ]),
        new BingoItem("red sneakers", ["feet", "shoes", "flats", "red", "white", "stripes", ]),
        new BingoItem("yellow sneakers", ["feet", "shoes", "flats", "white", "yellow", "stripes", ]),
        new BingoItem("bobby pins", ["head", "hair", "gem", "beaded", "silver", "blue", ]),
        new BingoItem("patterned barrette 1", ["head", "hair", "pattern", "red", ]),
        new BingoItem("patterned barrette 2", ["head", "hair", "pattern", "blue", ]),
        new BingoItem("patterned barrette 3", ["head", "hair", "pattern", "orange", "yellow", ]),
        new BingoItem("black headband", ["head", "hair", "black", ]),
        new BingoItem("blue headband", ["head", "hair", "blue", ]),
        new BingoItem("green headband", ["head", "hair", "green", ]),
        new BingoItem("orange headband", ["head", "hair", "orange", ]),
        new BingoItem("pink headband", ["head", "hair", "pink", ]),
        new BingoItem("purple headband", ["head", "hair", "purple", ]),
        new BingoItem("red headband", ["head", "hair", "red", ]),
        new BingoItem("yellow headband", ["head", "hair", "yellow", ]),
        new BingoItem("red double headband", ["head", "hair", "red", ]),
        new BingoItem("pink double headband", ["head", "hair", "pink", ]),
        new BingoItem("purple double headband", ["head", "hair", "purple", ]),
        new BingoItem("blue double headband", ["head", "hair", "blue", ]),
        new BingoItem("orange double headband", ["head", "hair", "orange", ]),
        new BingoItem("green double headband", ["head", "hair", "green", ]),
        new BingoItem("yellow double headband", ["head", "hair", "yellow", ]),
        new BingoItem("black double headband", ["head", "hair", "black", ]),
        new BingoItem("fabric headband 1", ["head", "hair", "pattern", "green", "floral", ]),
        new BingoItem("fabric headband 2", ["head", "hair", "pattern", "stripes", "animal", "black", "white", ]),
        new BingoItem("fabric headband 3", ["head", "hair", "pattern", "green", "plaid", ]),
        new BingoItem("fabric headband 4", ["head", "hair", "pattern", "brown", "polka-dot", ]),
        new BingoItem("fabric headband 5", ["head", "hair", "pattern", "pink", "floral", ]),
        new BingoItem("fabric headband 6", ["head", "hair", "pattern", "white", "polka-dot", ]),
        new BingoItem("fabric headband 7", ["head", "hair", "pattern", "red", "orange", "floral", ]),
        new BingoItem("fabric headband 8", ["head", "hair", "pattern", "red", "plaid", ]),
        new BingoItem("fabric headband 9", ["head", "hair", "pattern", "blue", "floral", ]),
        new BingoItem("fabric headband 10", ["head", "hair", "pattern", "floral", ]),
        new BingoItem("fabric headband 11", ["head", "hair", "pattern", "brown", "animal", ]),
        new BingoItem("fabric headband 12", ["head", "hair", "pattern", "pink", "floral", ]),
        new BingoItem("fabric headband 13", ["head", "hair", "pattern", "green", "floral", ]),
        new BingoItem("fabric headband 14", ["head", "hair", "pattern", "red", "orange", "brown", "floral", ]),
        new BingoItem("fabric headband 15", ["head", "hair", "pattern", "yellow", "animal", ]),
        new BingoItem("fabric headband 16", ["head", "hair", "pattern", "white", "floral", ]),
        new BingoItem("fabric headband 17", ["head", "hair", "pattern", "green", "polka-dot", ]),
        new BingoItem("black bow clips", ["head", "hair", "black", "bow", ]),
        new BingoItem("blue bow clips", ["head", "hair", "blue", "bow", ]),
        new BingoItem("green bow clips", ["head", "hair", "green", "bow", ]),
        new BingoItem("orange bow clips", ["head", "hair", "orange", "bow", ]),
        new BingoItem("pink bow clips", ["head", "hair", "pink", "bow", ]),
        new BingoItem("purple bow clips", ["head", "hair", "purple", "bow", ]),
        new BingoItem("red bow clips", ["head", "hair", "red", "bow", ]),
        new BingoItem("white bow clips", ["head", "hair", "white", "bow", ]),
        new BingoItem("yellow bow clips", ["head", "hair", "yellow", "bow", ]),
        new BingoItem("patterned bow clips 1", ["head", "hair", "pattern", "bow", "pink", ]),
        new BingoItem("patterned bow clips 2", ["head", "hair", "pattern", "bow", "red", ]),
        new BingoItem("patterned bow clips 3", ["head", "hair", "pattern", "bow", "blue", ]),
        new BingoItem("patterned bow clips 4", ["head", "hair", "pattern", "bow", "green", ]),
        new BingoItem("patterned bow clips 5", ["head", "hair", "pattern", "bow", "animal", ]),
        new BingoItem("brown claw", ["head", "hair", "brown", ]),
        new BingoItem("black claw", ["head", "hair", "black", ]),
        new BingoItem("red claw", ["head", "hair", "red", ]),
        new BingoItem("pink claw", ["head", "hair", "pink", ]),
        new BingoItem("purple claw", ["head", "hair", "purple", ]),
        new BingoItem("blue claw", ["head", "hair", "blue", ]),
        new BingoItem("orange claw", ["head", "hair", "orange", ]),
        new BingoItem("green claw", ["head", "hair", "green", ]),
        new BingoItem("yellow claw", ["head", "hair", "yellow", ]),
        new BingoItem("red baret", ["head", "hat", "red", ]),
        new BingoItem("purple baret", ["head", "hat", "purple", ]),
        new BingoItem("orange baseball cap", ["head", "hat", "orange", "brown", ]),
        new BingoItem("blue baseball cap", ["head", "hat", "blue", ]),
        new BingoItem("green baseball cap", ["head", "hat", "green", ]),
        new BingoItem("black cowboy hat", ["head", "hat", "red", "black", ]),
        new BingoItem("cowboy hat", ["head", "hat", "green", "brown", ]),
        new BingoItem("'earflap' hat", ["head", "hat", "winter", "blue", ]),
        new BingoItem("brown 'earflap' hat", ["head", "hat", "winter", "brown", ]),
        new BingoItem("fedora", ["head", "hat", "white", "orange", "brown", ]),
        new BingoItem("patterned fedora", ["head", "hat", "white", "black", "floral", "pattern", ]),
        new BingoItem("newsboy hat", ["head", "hat", "blue", "floral", ]),
        new BingoItem("patterned newsboy hat", ["head", "hat", "orange", "pink", "purple", "pattern", "floral", ]),
        new BingoItem("blue snow cap", ["head", "hat", "winter", "blue", ]),
        new BingoItem("snow cap", ["head", "hat", "winter", "pink", ]),
        new BingoItem("straw/sun hat", ["head", "hat", "summer", "red", ]),
        new BingoItem("patterned straw/sun hat", ["head", "hat", "summer", "green", "pattern", "floral", ]),
        new BingoItem("patterned tote 1", ["bag", "tote", "pattern", "stripes", "animal", "purple", "black", "white", ]),
        new BingoItem("patterned tote 2", ["bag", "tote", "pattern", "brown", "floral", ]),
        new BingoItem("patterned tote 3", ["bag", "tote", "pattern", "pink", "white", "polka-dot", ]),
        new BingoItem("patterned tote 4", ["bag", "tote", "pattern", "red", "orange", "floral", ]),
        new BingoItem("patterned tote 5", ["bag", "tote", "pattern", "blue", "floral", ]),
        new BingoItem("patterned tote 6", ["bag", "tote", "pattern", "green", "floral", ]),
        new BingoItem("patterned tote 7", ["bag", "tote", "pattern", "brown", "animal", ]),
        new BingoItem("patterned tote 8", ["bag", "tote", "pattern", "pink", "stripes", ]),
        new BingoItem("patterned tote 9", ["bag", "tote", "pattern", "pink", "white", "floral", ]),
        new BingoItem("patterned tote 10", ["bag", "tote", "pattern", "pink", "purple", "orange", "floral", ]),
        new BingoItem("patterned tote 11", ["bag", "tote", "pattern", "yellow", "black", "animal", ]),
        new BingoItem("patterned tote 12", ["bag", "tote", "pattern", "white", "pink", "floral", ]),
        new BingoItem("patterned tote 13", ["bag", "tote", "pattern", "black", "white", "floral", ]),
        new BingoItem("patterned tote 14", ["bag", "tote", "pattern", "yellow", "floral", ]),
        new BingoItem("patterned tote 15", ["bag", "tote", "pattern", "green", "stripes", ]),
        new BingoItem("brown woven tote", ["bag", "tote", "brown", ]),
        new BingoItem("orange woven tote", ["bag", "tote", "orange", ]),
        new BingoItem("yellow woven tote", ["bag", "tote", "yellow", ]),
        new BingoItem("blue change purse", ["bag", "blue", ]),
        new BingoItem("red change purse", ["bag", "red", ]),
        new BingoItem("pink change purse", ["bag", "pink", ]),
        new BingoItem("purple change purse", ["bag", "purple", ]),
        new BingoItem("orange change purse", ["bag", "orange", ]),
        new BingoItem("green change purse", ["bag", "green", ]),
        new BingoItem("yellow change purse", ["bag", "yellow", ]),
        new BingoItem("clutch", ["bag", "brown", "gold", ]),
        new BingoItem("green baguette", ["bag", "green", ]),
        new BingoItem("purple baguette", ["bag", "purple", ]),
        new BingoItem("patterned purse 1", ["bag", "pattern", "green", "polka-dot", ]),
        new BingoItem("patterned purse 2", ["bag", "pattern", "blue", "floral", ]),
        new BingoItem("patterned purse 3", ["bag", "pattern", "brown", "polka-dot", ]),
        new BingoItem("patterned purse 4", ["bag", "pattern", "red", "floral", ]),

        // recolored items
        new BingoItem("garnet gemstone earrings", ["head", "jewelry", "earrings", "gem", "red", ]),
        new BingoItem("purple gemstone earrings", ["head", "jewelry", "earrings", "gem", "purple", ]),
        new BingoItem("teal gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ]),
        new BingoItem("silver gemstone earrings", ["head", "jewelry", "earrings", "gem", "silver", ]),
        new BingoItem("green gemstone earrings", ["head", "jewelry", "earrings", "gem", "green", ]),
        new BingoItem("ruby gemstone earrings", ["head", "jewelry", "earrings", "gem", "red", ]),
        new BingoItem("light green gemstone earrings", ["head", "jewelry", "earrings", "gem", "green", ]),
        new BingoItem("blue gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ]),
        new BingoItem("pink gemstone earrings", ["head", "jewelry", "earrings", "gem", "pink", ]),
        new BingoItem("yellow gemstone earrings", ["head", "jewelry", "earrings", "gem", "yellow", ]),
        new BingoItem("light blue gemstone earrings", ["head", "jewelry", "earrings", "gem", "blue", ]),

        new BingoItem("silver hoop earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ]),
        new BingoItem("gold hoop earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ]),

        new BingoItem("silver thick hoop earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ]),
        new BingoItem("gold thick hoop earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ]),

        new BingoItem("silver bubble earrings", ["head", "jewelry", "earrings", "hoop", "silver", "dangly", ]),
        new BingoItem("gold bubble earrings", ["head", "jewelry", "earrings", "hoop", "gold", "dangly", ]),

        new BingoItem("silver basic ring", ["hands", "jewelry", "ring", "silver", ]),
        new BingoItem("gold basic ring", ["hands", "jewelry", "ring", "gold", ]),

        new BingoItem("red solid heel", ["feet", "shoes", "heel", "red", ]),
        new BingoItem("pink solid heel", ["feet", "shoes", "heel", "pink", ]),
        new BingoItem("purple solid heel", ["feet", "shoes", "heel", "purple", ]),
        new BingoItem("blue solid heel", ["feet", "shoes", "heel", "blue", ]),
        new BingoItem("orange solid heel", ["feet", "shoes", "heel", "orange", ]),
        new BingoItem("green solid heel", ["feet", "shoes", "heel", "green", ]),
        new BingoItem("yellow solid heel", ["feet", "shoes", "heel", "yellow", ]),
        new BingoItem("black solid heel", ["feet", "shoes", "heel", "black", ]),

    ];
}

}
